-- Rag2OKF 知识库文档生命周期初始结构。
-- 本脚本面向新系统，不迁移存量账号，不创建固定 Seed，不包含数据库抢锁语义。
-- 新环境由部署人员手工执行，应用启动不执行 DDL。

CREATE TABLE kb_user (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    user_key CHAR(26) NOT NULL COMMENT '不可变用户业务标识，同时作为 Sa-Token loginId',
    email VARCHAR(254) NOT NULL COMMENT 'trim 并整体转小写后的登录邮箱',
    password_hash VARCHAR(255) NOT NULL COMMENT '带算法标识和随机盐的密码摘要',
    display_name VARCHAR(64) NOT NULL COMMENT '用户展示名称',
    avatar_url VARCHAR(512) NULL COMMENT '用户头像地址',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '账号状态：ACTIVE 启用，DISABLED 禁用',
    preference_json JSON NULL COMMENT '用户界面与处理偏好',
    last_login_at DATETIME(3) NULL COMMENT '最近一次成功登录时间',
    password_changed_at DATETIME(3) NOT NULL COMMENT '当前密码摘要生效时间',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_user_user_key (user_key),
    UNIQUE KEY uk_kb_user_email (email),
    KEY idx_kb_user_status_updated (status, updated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Rag2OKF 本地用户';

CREATE TABLE kb_model_connection (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    connection_key CHAR(26) NOT NULL COMMENT '不可枚举 Provider 连接业务标识',
    owner_user_id BIGINT NOT NULL COMMENT '连接所有者本地用户主键',
    provider_code VARCHAR(40) NOT NULL COMMENT '内置模板或 CUSTOM 厂商代码',
    provider_name VARCHAR(80) NOT NULL COMMENT '用户可识别的厂商名称',
    display_name VARCHAR(80) NOT NULL COMMENT '当前用户下唯一的连接展示名称',
    protocol_type VARCHAR(32) NOT NULL DEFAULT 'OPENAI_COMPATIBLE' COMMENT '调用协议类型',
    base_url VARCHAR(512) NOT NULL COMMENT '模型 API 根地址，运行时需执行 SSRF 安全校验',
    api_key_ciphertext VARBINARY(2048) NOT NULL COMMENT 'AES-GCM 加密后的 API Key 密文',
    api_key_nonce VARBINARY(32) NOT NULL COMMENT '每次加密生成的随机 nonce',
    key_version VARCHAR(32) NOT NULL COMMENT '部署主密钥版本，不保存主密钥',
    api_key_mask VARCHAR(32) NOT NULL COMMENT '仅供界面识别的不可逆固定掩码',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '连接状态：ACTIVE 或 DISABLED',
    last_test_status VARCHAR(20) NULL COMMENT '最近一次安全化连接测试状态',
    last_test_at DATETIME(3) NULL COMMENT '最近一次连接测试时间',
    last_test_error_code VARCHAR(64) NULL COMMENT '最近一次安全化连接测试错误码',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_model_connection_key (connection_key),
    UNIQUE KEY uk_kb_model_connection_owner_display (owner_user_id, display_name),
    KEY idx_kb_model_connection_owner_status_updated (owner_user_id, status, updated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户级 Provider 连接与加密凭证';

CREATE TABLE kb_model_profile (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    profile_key CHAR(26) NOT NULL COMMENT '不可枚举模型档案业务标识',
    owner_user_id BIGINT NOT NULL COMMENT '档案所有者本地用户主键，必须与连接所有者一致',
    connection_id BIGINT NOT NULL COMMENT '所属 Provider 连接主键',
    model_type VARCHAR(24) NOT NULL COMMENT '模型调用类型：CHAT 或 EMBEDDING',
    model_name VARCHAR(160) NOT NULL COMMENT '厂商实际模型 ID',
    dimensions INT NULL COMMENT 'Embedding 输出维度提示，需由模型测试校验',
    parameters_json JSON NOT NULL DEFAULT (JSON_OBJECT()) COMMENT '温度、超时和重试等受控参数快照',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '档案状态：ACTIVE 或 DISABLED',
    last_test_status VARCHAR(20) NULL COMMENT '最近一次模型能力测试状态',
    last_test_at DATETIME(3) NULL COMMENT '最近一次模型测试时间',
    last_test_error_code VARCHAR(64) NULL COMMENT '最近一次安全化模型测试错误码',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_model_profile_key (profile_key),
    UNIQUE KEY uk_kb_model_profile_owner_connection_type_name (owner_user_id, connection_id, model_type, model_name),
    KEY idx_kb_model_profile_owner_type_status (owner_user_id, model_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户可复用的模型档案';

CREATE TABLE kb_model_binding (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    binding_key CHAR(26) NOT NULL COMMENT '不可枚举用途绑定业务标识',
    knowledge_base_id BIGINT NOT NULL COMMENT '所属知识库主键',
    usage_type VARCHAR(40) NOT NULL COMMENT '知识库模型用途，由应用层白名单控制',
    model_profile_id BIGINT NOT NULL COMMENT '当前用途选中的模型档案主键',
    config_json JSON NOT NULL DEFAULT (JSON_OBJECT()) COMMENT '当前用途的非敏感受控参数快照',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '绑定状态：ACTIVE 或 DISABLED',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_model_binding_key (binding_key),
    UNIQUE KEY uk_kb_model_binding_knowledge_usage (knowledge_base_id, usage_type),
    KEY idx_kb_model_binding_profile_status (model_profile_id, status),
    KEY idx_kb_model_binding_knowledge_status (knowledge_base_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='知识库按用途选择模型档案的关系';

CREATE TABLE kb_workspace (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    workspace_key CHAR(26) NOT NULL COMMENT '工作空间业务标识',
    name VARCHAR(128) NOT NULL COMMENT '工作空间名称',
    workspace_type VARCHAR(20) NOT NULL COMMENT '空间类型：PERSONAL 个人，ENTERPRISE 企业预留',
    owner_user_id BIGINT NOT NULL COMMENT '空间所有者用户主键',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '工作空间状态',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_workspace_workspace_key (workspace_key),
    UNIQUE KEY uk_kb_workspace_type_owner (workspace_type, owner_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='知识工作空间';

CREATE TABLE kb_workspace_member (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    workspace_id BIGINT NOT NULL COMMENT '工作空间主键',
    user_id BIGINT NOT NULL COMMENT '本地用户主键',
    local_role VARCHAR(32) NOT NULL COMMENT '本地角色：ADMIN 或 KNOWLEDGE_USER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '成员状态',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_workspace_member_workspace_user (workspace_id, user_id),
    KEY idx_kb_workspace_member_user_status (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='工作空间成员关系';

CREATE TABLE kb_knowledge_base (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    knowledge_base_key CHAR(26) NOT NULL COMMENT '知识库业务标识',
    workspace_id BIGINT NOT NULL COMMENT '所属工作空间主键',
    name VARCHAR(128) NOT NULL COMMENT '知识库名称',
    description VARCHAR(1000) NULL COMMENT '知识库说明',
    auto_parse TINYINT(1) NOT NULL DEFAULT 0 COMMENT '上传后是否自动解析',
    auto_publish TINYINT(1) NOT NULL DEFAULT 0 COMMENT '解析成功后是否自动发布',
    parser_profile VARCHAR(64) NOT NULL COMMENT '默认解析器 Profile 标识',
    chunk_profile_json JSON NOT NULL COMMENT '默认分块策略快照',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '知识库状态',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_knowledge_base_key (knowledge_base_key),
    KEY idx_kb_knowledge_base_workspace_status_updated (workspace_id, status, updated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='知识库及默认处理策略';

CREATE TABLE kb_source_document (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    document_key CHAR(26) NOT NULL COMMENT '文档逻辑业务标识',
    knowledge_base_id BIGINT NOT NULL COMMENT '所属知识库主键',
    display_name VARCHAR(255) NOT NULL COMMENT '文档展示名称',
    current_document_version_id BIGINT NULL COMMENT '当前不可变文件版本主键',
    current_parse_revision_id BIGINT NULL COMMENT '当前解析 Revision 主键',
    current_chunk_revision_id BIGINT NULL COMMENT '当前解析侧分块 Revision 主键',
    active_publication_revision_id BIGINT NULL COMMENT '当前生效发布 Revision 主键',
    parse_status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '当前解析状态：NOT_STARTED、QUEUED、RUNNING、SUCCEEDED、FAILED',
    publish_status VARCHAR(20) NOT NULL DEFAULT 'UNPUBLISHED' COMMENT '当前发布状态：UNPUBLISHED、PUBLISHING、PUBLISHED、PUBLISH_FAILED',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_source_document_key (document_key),
    KEY idx_kb_source_document_knowledge_updated (knowledge_base_id, updated),
    KEY idx_kb_source_document_active_publication (active_publication_revision_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='源文档逻辑身份与当前指针';

CREATE TABLE kb_document_version (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    version_key CHAR(26) NOT NULL COMMENT '不可变文件版本业务标识',
    source_document_id BIGINT NOT NULL COMMENT '源文档主键',
    object_key VARCHAR(512) NOT NULL COMMENT 'MinIO 系统对象 key',
    original_filename VARCHAR(255) NOT NULL COMMENT '上传时原始文件名',
    content_type VARCHAR(128) NOT NULL COMMENT '服务端识别的媒体类型',
    file_extension VARCHAR(32) NOT NULL COMMENT '规范化文件扩展名',
    size_bytes BIGINT NOT NULL COMMENT '文件字节数',
    sha256 CHAR(64) NOT NULL COMMENT '文件内容 SHA-256',
    upload_actor_id BIGINT NOT NULL COMMENT '上传用户主键',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_document_version_key (version_key),
    UNIQUE KEY uk_kb_document_version_object_key (object_key),
    KEY idx_kb_document_version_document_created (source_document_id, created)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='不可变文档文件版本';

CREATE TABLE kb_parse_revision (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    parse_revision_key CHAR(26) NOT NULL COMMENT '解析 Revision 业务标识',
    source_document_id BIGINT NOT NULL COMMENT '源文档主键',
    document_version_id BIGINT NOT NULL COMMENT '被解析的文件版本主键',
    parser_profile_json JSON NOT NULL COMMENT '解析器 Profile 输入快照',
    parser_trace_json JSON NULL COMMENT '解析器选择与执行轨迹',
    manifest_object_key VARCHAR(512) NULL COMMENT '解析结果 manifest 对象 key',
    anchor_manifest_object_key VARCHAR(512) NULL COMMENT '来源锚点 manifest 对象 key',
    block_count INT NOT NULL DEFAULT 0 COMMENT '解析块数量',
    status VARCHAR(20) NOT NULL COMMENT '解析 Revision 状态',
    error_code VARCHAR(64) NULL COMMENT '安全化错误码',
    error_message VARCHAR(500) NULL COMMENT '安全化错误摘要',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_parse_revision_key (parse_revision_key),
    KEY idx_kb_parse_revision_document_created (source_document_id, created),
    KEY idx_kb_parse_revision_version_status (document_version_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='不可变解析结果及执行轨迹';

CREATE TABLE kb_chunk_revision (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    chunk_revision_key CHAR(26) NOT NULL COMMENT '分块 Revision 业务标识',
    source_document_id BIGINT NOT NULL COMMENT '源文档主键',
    parse_revision_id BIGINT NOT NULL COMMENT '所属解析 Revision 主键',
    chunk_profile_json JSON NOT NULL COMMENT '分块策略输入快照',
    manifest_object_key VARCHAR(512) NULL COMMENT '分块 manifest 对象 key',
    parent_count INT NOT NULL DEFAULT 0 COMMENT '父分块数量',
    child_count INT NOT NULL DEFAULT 0 COMMENT '子分块数量',
    content_hash CHAR(64) NULL COMMENT '规范化分块集合内容摘要',
    status VARCHAR(20) NOT NULL COMMENT '分块 Revision 状态',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_chunk_revision_key (chunk_revision_key),
    KEY idx_kb_chunk_revision_document_created (source_document_id, created),
    KEY idx_kb_chunk_revision_parse_status (parse_revision_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='解析侧可替换分块集合';

CREATE TABLE kb_publication_revision (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    publication_revision_key CHAR(26) NOT NULL COMMENT '发布 Revision 业务标识',
    source_document_id BIGINT NOT NULL COMMENT '源文档主键',
    document_version_id BIGINT NOT NULL COMMENT '发布快照文件版本主键',
    parse_revision_id BIGINT NOT NULL COMMENT '发布快照解析 Revision 主键',
    chunk_revision_id BIGINT NOT NULL COMMENT '发布快照分块 Revision 主键',
    manifest_object_key VARCHAR(512) NULL COMMENT '发布 manifest 对象 key',
    projection_index VARCHAR(128) NULL COMMENT 'ES 物理投影索引',
    projection_count INT NOT NULL DEFAULT 0 COMMENT '写入 ES 的分块数量',
    status VARCHAR(20) NOT NULL COMMENT '发布状态',
    trigger_type VARCHAR(20) NOT NULL COMMENT '触发方式：MANUAL 或 AUTO',
    error_code VARCHAR(64) NULL COMMENT '安全化错误码',
    error_message VARCHAR(500) NULL COMMENT '安全化错误摘要',
    published_at DATETIME(3) NULL COMMENT '成功发布时间',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_publication_revision_key (publication_revision_key),
    KEY idx_kb_publication_revision_document_created (source_document_id, created),
    KEY idx_kb_publication_revision_status_updated (status, updated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='发布快照与 Elasticsearch 投影元数据';

CREATE TABLE kb_processing_task (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    task_key CHAR(26) NOT NULL COMMENT '异步任务业务标识',
    workspace_id BIGINT NOT NULL COMMENT '所属工作空间主键',
    knowledge_base_id BIGINT NOT NULL COMMENT '所属知识库主键',
    source_document_id BIGINT NOT NULL COMMENT '目标源文档主键',
    task_type VARCHAR(32) NOT NULL COMMENT '任务类型：PARSE、RECHUNK 或 PUBLISH',
    input_revision_key CHAR(26) NULL COMMENT '任务输入 Revision 业务标识',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '调用方幂等键',
    status VARCHAR(20) NOT NULL COMMENT '任务状态',
    stage VARCHAR(32) NULL COMMENT '当前执行阶段',
    progress INT NOT NULL DEFAULT 0 COMMENT '进度百分比，范围 0 到 100',
    attempt INT NOT NULL DEFAULT 0 COMMENT '已执行次数',
    max_attempts INT NOT NULL DEFAULT 3 COMMENT '最大执行次数',
    next_run_at DATETIME(3) NULL COMMENT '下次候选执行时间',
    execution_owner VARCHAR(128) NULL COMMENT '最近一次执行实例标识，不表示数据库锁',
    heartbeat_at DATETIME(3) NULL COMMENT '最近执行心跳时间',
    execution_deadline DATETIME(3) NULL COMMENT '执行租约恢复期限，不表示数据库锁',
    error_code VARCHAR(64) NULL COMMENT '安全化错误码',
    error_message VARCHAR(500) NULL COMMENT '安全化错误摘要',
    payload_json JSON NULL COMMENT '任务输入快照',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_processing_task_key (task_key),
    UNIQUE KEY uk_kb_processing_task_idempotency (source_document_id, task_type, idempotency_key),
    KEY idx_kb_processing_task_status_next_run (status, next_run_at),
    KEY idx_kb_processing_task_document_created (source_document_id, created)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='异步处理、幂等和崩溃恢复事实';

CREATE TABLE kb_outbox_event (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    event_key CHAR(26) NOT NULL COMMENT '事件业务标识和投递幂等键',
    aggregate_type VARCHAR(64) NOT NULL COMMENT '聚合类型',
    aggregate_key CHAR(26) NOT NULL COMMENT '聚合业务标识',
    event_type VARCHAR(64) NOT NULL COMMENT '事件类型',
    payload_json JSON NOT NULL COMMENT '事件载荷快照',
    status VARCHAR(20) NOT NULL COMMENT '投递状态',
    attempt INT NOT NULL DEFAULT 0 COMMENT '已投递次数',
    next_run_at DATETIME(3) NULL COMMENT '下次候选投递时间',
    published_at DATETIME(3) NULL COMMENT '成功投递时间',
    created DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_outbox_event_key (event_key),
    KEY idx_kb_outbox_event_status_next_run (status, next_run_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='事务 Outbox 事件';
